### ISSUE TITLE
Update Copy to Clipboard feature

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#110]
The Copy to Clipboard is a great feature, however, there are two issues: 

1. When a user clicks the Copy to Clipboard icon, a message appears that pushes the button down, causing the card to be resized. The card should not resize.
2. There is no interaction when hovering over the Copy to Clipboard icon. The cursor should change and/or the icon should change color to indicate that it's an action.

**Comment by lil-dev16** [comment]
Hello, I'll work on this can I be assigned this

**Comment by devocoe** [comment]
I already fixed this issue please review my pr

**Comment by kiNapSter** [comment]
Hello @JasonFritsche, Can I work on this issue if it has not been assigned?

**Comment by JasonFritsche** [comment]
@kiNapSter this issue has been resolved. Please feel free to create an issue if you see something you'd like to work on.
