### ISSUE TITLE
Card should animate on hover

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#112]
The card should have some kind of animation when a user hovers over it. This could be subtle. I am thinking adding box shadow and/or adding some kind of elevation animation to the card. Use your best judgement and have fun!

**Comment by kiNapSter** [comment]
Hello @JasonFritsche . Is this issue still up for grabs? I would love to be assigned to this

**Comment by JasonFritsche** [comment]
@kiNapSter all yours!
