### ISSUE TITLE
Create Dark Theme and Theme Toggle

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#117]
Dark Themes are trendy and are my personal preference. It would be awesome if the site had a dark/light theme toggle. 

For this issue please resolve the following:

- create a dark theme
- create a light theme (can use the color theme we have now or create a new one)
- implement a theme toggle in the nav/menu
- implement the [prefers color scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS feature.

Please use your best judgement when implementing these features. Also, please keep a11y in mind.

**Comment by anayatkhan1** [comment]
Hello @JasonFritsche , i would like work on this issue

can you assign me

**Comment by JasonFritsche** [comment]
@anayatkhan1 All yours!
