### ISSUE TITLE
Add header 

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#31]
This could be a simple navbar with a title in it. Great issue for Hacktoberfest 2020!

**Comment by pallavithakare28** [comment]
Can you please assign me this. Thanks.

**Comment by JasonFritsche** [comment]
@pallavithakare28  I've assigned the issue to you.

**Comment by pallavithakare28** [comment]
@JasonFritsche  Thanks and I'll make a PR in October.
I just have to " add simple navbar in 'index.html'" right?

**Comment by JasonFritsche** [comment]
Please use the materialize css framework navbar component.
