### ISSUE TITLE
Change quote font 

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#33]
The quote font should be changed to something a bit more stylish. Keep it legible, nothing too over the top.

**Comment by louisefindlay23** [comment]
Happy to try a few font, @JasonFritsche.

**Comment by JasonFritsche** [comment]
Sounds good @louisefindlay23

**Comment by louisefindlay23** [comment]
Sure, @JasonFritsche. Created the Google Font performance issue in #35.
