### ISSUE TITLE
Cards should remain a consistent size

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#36]
Currently the cards are sized based off the image size and quote size. The card should remain a static height and not change.

**Comment by ThePsyk3y** [comment]
Hello, Can i take this Issue? And Submit the PR in October for Hacktober Fest?

**Comment by JasonFritsche** [comment]
You sure can! Please try to use any utility classes from the materialize library first. If that doesn't work then another approach is fine.

**Comment by ThePsyk3y** [comment]
I did try them, but it seems that even the 'large' size seems a little small to accommodate all the text from the quote.
So I just used regular CSS with flexbox. Is that alright?

**Comment by JasonFritsche** [comment]
@ThePsyk3y That's totally fine.
