### ISSUE TITLE
The Cat Image is not showing up

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#43]
There was a change recently that caused the cat images to now show up in the card.

**Comment by 4Rebin** [comment]
I  like to work with this issue.

**Comment by Mayur500** [comment]
can i work on this issue

**Comment by guptabhaskar** [comment]
Please assign me this issue @JasonFritsche.

**Comment by JasonFritsche** [comment]
Issue has been assigned to @4Rebin. He was first to request.
