### ISSUE TITLE
The total page height should be 100vh

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#44]
Currently, I have to scroll to see the footer. Please update the total height of the page (I should not be able to scroll).

**Comment by aayushwadhwa1** [comment]
please assign this to me

**Comment by Joshuafolorunsho** [comment]
@JasonFritsche I could help solve that

**Comment by JasonFritsche** [comment]
I've assigned the issue to @aayushwadhwa1, he was first to request.

**Comment by Joshuafolorunsho** [comment]
Oh! Alright @JasonFritsche.. Made a pull request already to solve the issue. You could close it. Cheer!
