### ISSUE TITLE
Remove the hyperlinks from the Header

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#45]
Please remove the hyper links from the header (contact us, etc), they do not link to anything. The header should just have some fancy looking text that says "Motivational Cats".

**Comment by Apoorve73** [comment]
You want to replace "Contact Us", "About Cats" by "Motivational Cats". Rt?

**Comment by robin828** [comment]
Can you assign this issue to me? @JasonFritsche

**Comment by JasonFritsche** [comment]
I want to totally remove the links. The header should just have a nice looking title displayed.

**Comment by tanujajoshi1** [comment]
I want to work on this

**Comment by Apoorve73** [comment]
Awesome! I can do that, if that's okay. @JasonFritsche

**Comment by JasonFritsche** [comment]
Yeah, I will assign to you @Apoorve73

**Comment by Apoorve73** [comment]
@JasonFritsche Kindly check PR #54 and a related NEW ISSUE #53
