### ISSUE TITLE
[UPDATE] Black background

### ISSUE THREAD

**Issue by Apoorve73** [JasonFritsche/motivationalCats#53]
# Overview
Add black background for a soother experience with header for Issue #45 .

# Tasks
- [x] Change Background to black

![Screenshot from 2020-10-03 01-59-52](https://user-images.githubusercontent.com/55204045/94967488-cce95900-051c-11eb-9f63-af3f561856dd.png)

**Comment by Hannibal404** [comment]
I'd like to work on this
