### ISSUE TITLE
Add padding in the header (font needs space on bottom)

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#56]
The font in the header is too close to the bottom of the header/navbar. Add some space.

**Comment by caseymhunt** [comment]
Please add "hacktoberfest" topic to the repository so I may get credit for my PR. Thank you!

![image](https://user-images.githubusercontent.com/2065615/95002623-bc2bf800-059b-11eb-8f30-1d3f76cd0555.png)

**Comment by JasonFritsche** [comment]
@caseymhunt  thank you for bringing this to my attention.

**Comment by GeoBrodas** [comment]
Is your issue resolved??

**Comment by hambali999** [comment]
Hi can you assign me to the task? This i my first hacktoberfest!

**Comment by IraTeixeira** [comment]
Hey, I'd like to fix it! Can you assign me?

**Comment by chandankumar1307** [comment]
Hey :) @JasonFritsche 
Just assign me this issue and it will be solved very soon.
I have a lot of experience in this
