### ISSUE TITLE
The quote button is not visibile when the quote is too long

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#67]
The button to get another quote should always be visible. Please tell me how you will fix this and if it is a sound solution I will assign the task to you.

**Comment by flyingfisch** [comment]
I would set `height` to `90%` and `overflow-y` to `auto`, screenshot of the fix below:

![Screenshot_2020-10-05 Motivational Cats](https://user-images.githubusercontent.com/1307001/95107970-9d973f80-0708-11eb-8c80-39470ff3c57b.png)
![Screenshot_2020-10-05 Motivational Cats(1)](https://user-images.githubusercontent.com/1307001/95107974-9f610300-0708-11eb-85eb-d27ae3433c58.png)

**Comment by JasonFritsche** [comment]
@flyingfisch I will assign this issue to you.
