### ISSUE TITLE
Height of page is causing user to have to scroll to see footer

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#68]
There should never be scrolling, everything should fit in the browser (header, body, footer) with no scrolling required.

**Comment by SvA1** [comment]
Hi @JasonFritsche . I want to try to help, can you assign this to me?

**Comment by JasonFritsche** [comment]
@SvA1 I will assign this issue to you.

**Comment by SvA1** [comment]
Thanks!
