### ISSUE TITLE
Site is not mobile friendly

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#74]
The main culprit with regard to the site not being mobile friendly is the navbar/header. However, other items may need to be looked at as well. You'll probably need to use media queries, but not 100% sure as this site uses materialize library, so maybe there is a utility function to help out with the nav. Either way, the nav/header should not overlap the card on smaller screens.

**Comment by rootEnginear** [comment]
I'll working on this
