### ISSUE TITLE
Fix header responsive sizing

### ISSUE THREAD

**Issue by rachael-t** [JasonFritsche/motivationalCats#87]
The header resizes well for small devices, but on larger desktop views the H1 overflows out of the header background, and white space is also introduced (see images below). Ideally, the header would be responsive to any device and screen size. 

<img width="1917" alt="Screen Shot 2021-10-18 at 6 22 54 PM" src="https://user-images.githubusercontent.com/54180641/137824279-b368b2e6-7f77-44a9-a355-40d319137da3.png">

<a href="https://www.loom.com/share/a83f2495446942858c8198d10defbfc7">
    <p>Motivational Cats - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/a83f2495446942858c8198d10defbfc7-with-play.gif">
  </a>

**Comment by JasonFritsche** [comment]
@rachael-t Thanks for creating this issue. I can assign it to you if you would like to work on it.

**Comment by rachael-t** [comment]
@JasonFritsche that would be great, thank you! 😄
