### ISSUE TITLE
Create CSS variables for colors

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#96]
The stylesheet will be easier to maintain if we have css variables defined for colors. We can create variables for other properties as well in the future.

**Comment by vikkyava** [comment]
Hi, can you assign me this issue? I'd love to work on it

**Comment by JasonFritsche** [comment]
@vikkyava all yours!

**Comment by GustavoGomesRibeiro** [comment]
@JasonFritsche Please assign me.

**Comment by JasonFritsche** [comment]
@GustavoGomesRibeiro 
This ticket is already assigned. Please feel free to look at the other open issues!

**Comment by JasonFritsche** [comment]
@vikkyava , be advised a PR was merged for this recently. Please make sure you have the latest code. Please feel free to create additional variables for sizes, etc.
