### ISSUE TITLE
Add animation/style change on hover of "Get Motivated" card button

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#97]
The card button is a bit boring. It should change color, scale in size a bit, or something else that's fun when a user hovers over it. Use your best judgement and have fun!

**Comment by adetoye-dev** [comment]
Hi, can you assign this to me? I'd love to work on it

**Comment by JasonFritsche** [comment]
@adetoye-dev it's all yours!
