### ISSUE TITLE
Update Color Theme of Entire Site

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#98]
This color palette/theme has been in place for about a year now. Let's breathe some new life in to this app by updating the color theme. This will include changing the background color, footer, navbar, card background color, and card button color.

If #96 is already closed, please adhere to using CSS variables.

**Comment by Siddhanthota** [comment]
Can you please assign this to me? Also, would you like color gradients in background? (Just an idea)

**Comment by JasonFritsche** [comment]
@Siddhanthota Please feel free to experiment with gradients.

**Comment by Sah314** [comment]
can you please assign this to me?

**Comment by RAHUL14KUMAR** [comment]
hi i am a hacktoberfest participant . can you please assign these issue to me?

**Comment by JasonFritsche** [comment]
@Sah314  @RAHUL14KUMAR this issue is already assigned.
