### ISSUE TITLE
Change Quote Text Font-Family

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/motivationalCats#99]
I was thinking of using something like [this](https://fonts.google.com/specimen/Courgette?category=Handwriting).

**Comment by Siddhanthota** [comment]
Looks good to me. Can you assign me this so that i can start working on it?

**Comment by GustavoGomesRibeiro** [comment]
@JasonFritsche Please assign me.

**Comment by JasonFritsche** [comment]
@Siddhanthota all yours!
